apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-service
  namespace: paw-pin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-service
  template:
    metadata:
      labels:
        app: central-service
    spec:
      containers:
      - name: central-service
        image: 574067620045.dkr.ecr.eu-central-1.amazonaws.com/paw-pin-central-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9092
