apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: paw-pin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: 574067620045.dkr.ecr.eu-central-1.amazonaws.com/paw-pin-backend:latest
        ports:
        - containerPort: 8080
#        env:
#        - name: SPRING_PROFILES_ACTIVE
#          value: prod
#        envFrom:
#        - secretRef:
#            name: backend-secrets
